"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from pathlib import Path

APP = ['nagaraotaku_gui.py']
DATA_FILES = []
OPTIONS = {
    'iconfile':'config/fig/logo.ico',
}

def addImageFiles():
    for path in Path("config/fig").glob("*.jpg"):
        element = "config/fig", [path]
        DATA_FILES.append(element)

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
